@startuml
title <size:24>Container View: LivingDoc System</size>

set separator none
left to right direction

<style>
  root {
    BackgroundColor: #ffffff
    FontColor: #444444
  }
</style>

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

Person(Usuário, "Usuário", $descr="Um usuário do sistema que realiza pedidos.", $tags="", $link="")

System_Boundary("LivingDocSystem_boundary", "LivingDoc System", $tags="") {
  Container(LivingDocSystem.WebAPI, "Web API", $techn="ASP.NET Core", $descr="API desenvolvida em .NET 8.", $tags="", $link="")
  ContainerDb(LivingDocSystem.Database, "Database", $techn="PostgreSQL", $descr="Armazena dados de usuários e pedidos.", $tags="", $link="")
}

Rel(Usuário, LivingDocSystem.WebAPI, "Faz requisições para", $techn="HTTPS", $tags="", $link="")
Rel(LivingDocSystem.WebAPI, LivingDocSystem.Database, "Lê e escreve dados em", $techn="EF Core", $tags="", $link="")

SHOW_LEGEND(true)
hide stereotypes
@enduml