@startuml
title <size:24>System Context View: LivingDoc System</size>

set separator none
left to right direction

<style>
  root {
    BackgroundColor: #ffffff
    FontColor: #444444
  }
</style>

!include <C4/C4>
!include <C4/C4_Context>

Person(Usuário, "Usuário", $descr="Um usuário do sistema que realiza pedidos.", $tags="", $link="")
System(LivingDocSystem, "LivingDoc System", $descr="Sistema de exemplo para documentação viva.", $tags="", $link="")

Rel(Usuário, LivingDocSystem, "Faz requisições para", $techn="HTTPS", $tags="", $link="")

SHOW_LEGEND(true)
hide stereotypes
@enduml